#!/usr/bin/env sh

WIFI_NAME=$(iwgetid | awk -F '"' '{print $2}')
OFF_ICON=" "
TAIL="#[fg=colour237] ⦁ "

[ "$WIFI_NAME" = "$OFF_ICON" ] && printf "#[fg=red]%s" "$WIFI_NAME$TAIL" || printf "%s" "$WIFI_NAME$TAIL"
