theme = "dracula-clear" 

[editor]  
auto-completion = true  
auto-format = true  
auto-save = true
bufferline = "always"  
completion-trigger-len = 1
color-modes = true  
cursorline = true  
line-number = "relative"  
mouse = false  
shell = ["fish", "-c"]  

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.file-picker]  
hidden = false  

[editor.cursor-shape]  
insert = "bar"  
normal = "block"  
select = "underline"  

[editor.indent-guides]  
render = true  

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[keys.normal]  
a = ["append_mode", "collapse_selection"]
E = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]  
G = "goto_last_line"  
N = ["extend_to_line_bounds", "delete_selection", "paste_after"]  
pagedown = ["half_page_down", "goto_window_center"]  
pageup = ["half_page_up", "goto_window_center"]  

h="move_char_left"  
n="move_line_down"  
e="move_line_up"  
i="move_char_right"  

k="insert_mode"  
K="insert_at_line_start"  

o="open_below"  
O="open_above"  

j="move_next_word_end"  
J="move_next_long_word_end"  

l="search_next"  
L="search_prev"  

"C-/" = ["toggle_comments"] 

C-h = "goto_previous_buffer"
C-i = "goto_next_buffer"
C-x = ":buffer-close"

[keys.normal.space.w]  
n="jump_view_left"  
e="jump_view_down"  
i="jump_view_up"  
o="jump_view_right"  

[keys.normal.g]  
h = "hover"  
a = "code_action"  

[keys.select]  
G = "goto_last_line"  

h="move_char_left"  
n="move_line_down"  
e="move_line_up"  
i="move_char_right"  

k="insert_mode"  
K="insert_at_line_start"  

o="open_below"  
O="open_above"  

j="move_next_word_end"  
J="move_next_long_word_end"  

l="search_next"  
L="search_prev"  

[keys.normal.z]  
n="scroll_down"  
e="scroll_up"  

[keys.normal.Z]  
n="scroll_down"  
e="scroll_up"  

# [keys.insert]  
# f = { w = "normal_mode" } # Maps `fw` to exit insert mode  

[editor.statusline]  
left = ["mode", "spinner"]  
center = ["file-name"]  
right = ["file-encoding", "file-line-ending", "file-type"]  
separator = "|"  
mode.normal = "NORMAL"  
mode.insert = "INSERT"  
mode.select = "SELECT"  
